name: Node.js CI

on:
  push:
    branches: [ tomasbozzo/ch46/integrate-with-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd functions
          npm ci
          npm run test
          npm run build
          npm run functional-tests
      - run: npm ci
