name: Node.js CI

on:
  push:
    branches: [ tomasbozzo/ch46/integrate-with-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Functions - Install
        working-directory: functions
        run: npm ci

      - name: Functions - Test
        working-directory: functions
        run: npm run test

      - name: Functions - Build
        working-directory: functions
        run: npm run build

      - name: Functions - Functional tests
        working-directory: functions
        run: npm run functional-tests
