name: Node.js CI

on:
  push:
    branches: [ tomasbozzo/ch46/integrate-with-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build-functions:
    name: Build Functions
    defaults:
      run:
        working-directory: functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Functional tests
        run: npm run functional-tests

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: functions-build
          path:

  build-blog-app:
    name: Build Hosting - Blog App
    defaults:
      run:
        working-directory: hosting/blog-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

  functional-tests:
    name: End-to-end functional tests
    needs: [build-functions, build-blog-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Functions - Install
        working-directory: functions
        run: npm ci

      - name: Functions - Build
        working-directory: functions
        run: npm run build

      - name: Hosting - Blog App - Install
        working-directory: hosting/blog-app
        run: npm ci

      - name: Hosting - Blog App - Build
        working-directory: hosting/blog-app
        run: npm run build

      - name: Functional tests - Install
        run: npm ci

      - name: Functional tests - Run
        run: npm run functional-tests